pub mod day08;

// 262 is too high

#[cfg(test)]
mod tests {
    use common::PuzzleParts;

    use crate::day08::day08::Day08;

    #[test]
    fn part_1() {
        let input = String::from(
            "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............",
        );
        let mut puzz = Day08::new(&input);
        assert_eq!(puzz.part_one(), "14");
    }
    #[test]
    fn part_2() {
        let input = String::from(
            "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............",
        );
        let mut puzz = Day08::new(&input);
        assert_eq!(puzz.part_two(), Some(String::from("34")));
    }
}
