let {makeRollDie} = require('./day21')

let rollDie = makeRollDie()
console.log(rollDie())
console.log(rollDie())
console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
// console.log(rollDie())
